"""relations between tables 2

Revision ID: 2acd5623ebdf
Revises: b4d8eef71b19
Create Date: 2025-04-01 18:27:20.793072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2acd5623ebdf'
down_revision = 'b4d8eef71b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_author')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_surname_uc', ['name', 'surname'])

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), sa.ForeignKey('author.id', name='fk_book_author')))
        batch_op.drop_index('ix_book_author')
        batch_op.create_foreign_key('fk_book_author', 'author', ['author_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('checkout_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_checkout_record_author')
        batch_op.drop_index('ix_checkout_record_title')
        batch_op.create_foreign_key('fk_checkout_record_book', 'book', ['book_id'], ['id'])
        batch_op.drop_column('author')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_checkout_record_title', ['title'], unique=False)
        batch_op.create_index('ix_checkout_record_author', ['author'], unique=False)
        batch_op.drop_column('book_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_book_author', ['author'], unique=1)
        batch_op.drop_column('author_id')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_author_name_surname', 'author', ['name', 'surname'])

    op.create_table('_alembic_tmp_author',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'surname', name='_name_surname_uc')
    )
    # ### end Alembic commands ###
