"""update is_borrowed

Revision ID: a1857bb21fec
Revises: 03ba479326d5
Create Date: 2025-04-01 19:24:30.795811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1857bb21fec'
down_revision = '03ba479326d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_is_borrowed', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_borrowed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_borrowed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('_is_borrowed')

    # ### end Alembic commands ###
